-- ==================================================
-- HOBBIER - Importación del catálogo de metas (mockapi.io -> Supabase)
-- Generado desde https://6a84625153754283b0b86fa4.mockapi.io/metas
-- 101 metas · 94 gustos · 100 intereses · 46 recursos
-- ==================================================
--
-- Pega este archivo completo en el SQL Editor y ejecútalo.
--
-- Es SEGURO ejecutarlo más de una vez: la identidad de cada actividad es su
-- `external_id`, así que una que ya esté importada se salta aunque le hayan
-- corregido el título en la API. Las relaciones van con ON CONFLICT DO NOTHING.
--
-- Requiere que `activities` tenga las columnas `external_id` y `source`.
--
-- Las metas quedan como actividades normales, así que se pueden aceptar,
-- completar, dan puntos y generan publicación igual que las del catálogo propio.

BEGIN;

-- 1. LAS METAS COMO ACTIVIDADES
-- La categoría llega por NOMBRE desde la API y se resuelve contra
-- activity_categories con LEFT JOIN: si no coincide con ninguna, la actividad
-- entra con category_id NULL (la interfaz la muestra como "Libre") en lugar de
-- perderse. Un INNER JOIN aquí descartaría actividades en silencio.
INSERT INTO public.activities
  (external_id, source, title, description, category_id, min_age, max_age, points_awarded, is_active)
-- Casts explícitos: si TODAS las metas traen el mismo campo en NULL (hoy pasa
-- con max_age), Postgres deduce esa columna del VALUES como `text` y el INSERT
-- falla contra la columna integer de la tabla.
SELECT v.external_id, 'mockapi', v.title, v.description, c.id,
       v.min_age::int, v.max_age::int, v.points::int, TRUE
FROM (VALUES
    ('1', 'Pinta algo que tengas frente a ti', 'Observa un objeto cercano y represéntalo con pintura, sin preocuparte por el resultado final.', 'Arte', 6, NULL, 20),
    ('2', 'Dibuja tu paisaje favorito de memoria', 'Sin usar referencias, dibuja un lugar que recuerdes con cariño.', 'Arte', 6, NULL, 15),
    ('3', 'Haz un boceto rápido de una persona cercana', 'Dibuja en pocos minutos a alguien que tengas cerca, sin buscar perfección.', 'Arte', 8, NULL, 15),
    ('4', 'Crea un collage con materiales reciclados', 'Usa recortes, papeles o materiales que tengas en casa para armar una composición.', 'Arte', 5, NULL, 20),
    ('5', 'Pinta un autorretrato abstracto', 'Represéntate a ti mismo usando formas y colores en lugar de un dibujo realista.', 'Arte', 8, NULL, 25),
    ('6', 'Diseña un logotipo imaginario para una marca inventada', 'Inventa una marca y diseña su logotipo usando cualquier herramienta digital.', 'Arte', 12, NULL, 20),
    ('7', 'Haz una escultura simple con plastilina o arcilla', 'Modela una figura pequeña con el material que tengas disponible.', 'Arte', 5, NULL, 15),
    ('8', 'Colorea un mandala durante 15 minutos', 'Dedica un tiempo tranquilo a colorear un patrón repetitivo.', 'Arte', 5, NULL, 10),
    ('9', 'Toma una foto artística de algo cotidiano', 'Encuentra belleza en un objeto común y captúralo con una composición interesante.', 'Arte', 10, NULL, 15),
    ('10', 'Sal a caminar 20 minutos', 'Da una caminata al aire libre, sin distracciones, prestando atención a tu entorno.', 'Deportes y Salud', 8, NULL, 15),
    ('11', 'Da un paseo en bicicleta por tu zona', 'Recorre tu barrio o un parque cercano en bicicleta durante al menos 15 minutos.', 'Deportes y Salud', 8, NULL, 20),
    ('12', 'Juega un partido de fútbol con amigos', 'Reúne a algunas personas y juega un partido informal.', 'Deportes y Salud', 8, NULL, 25),
    ('13', 'Haz 15 minutos de estiramientos', 'Realiza una rutina básica de estiramiento para todo el cuerpo.', 'Deportes y Salud', 6, NULL, 10),
    ('14', 'Sube y baja escaleras durante 10 minutos', 'Aprovecha unas escaleras cercanas para hacer un ejercicio cardiovascular simple.', 'Deportes y Salud', 6, NULL, 15),
    ('15', 'Haz una rutina de ejercicios en casa', 'Realiza una serie de ejercicios básicos sin necesidad de equipo.', 'Deportes y Salud', 10, NULL, 20),
    ('16', 'Practica lanzamientos con un balón', 'Dedica un tiempo a practicar puntería y control con un balón.', 'Deportes y Salud', 6, NULL, 15),
    ('17', 'Sal a trotar al aire libre', 'Trota a un ritmo cómodo durante al menos 15 minutos.', 'Deportes y Salud', 12, NULL, 20),
    ('18', 'Haz yoga durante 15 minutos', 'Sigue una secuencia sencilla de posturas de yoga para relajarte y activarte.', 'Deportes y Salud', 10, NULL, 15),
    ('19', 'Lee 15 páginas de un libro', 'Avanza en un libro que tengas pendiente, sin interrupciones.', 'Lectura y Aprendizaje', 8, NULL, 15),
    ('20', 'Aprende 10 palabras nuevas en otro idioma', 'Elige un idioma que te interese y memoriza 10 palabras útiles.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('21', 'Ve un documental educativo', 'Elige un documental sobre un tema que no conozcas bien y míralo completo.', 'Lectura y Aprendizaje', 10, NULL, 20),
    ('22', 'Escribe un resumen de lo último que leíste', 'Sintetiza en pocas líneas las ideas principales de tu lectura reciente.', 'Lectura y Aprendizaje', 10, NULL, 10),
    ('23', 'Investiga un tema que no conozcas', 'Elige un tema al azar y aprende sobre él durante al menos 20 minutos.', 'Lectura y Aprendizaje', 10, NULL, 20),
    ('24', 'Practica conjugaciones de verbos en otro idioma', 'Repasa las conjugaciones básicas de un idioma que estés aprendiendo.', 'Lectura y Aprendizaje', 12, NULL, 15),
    ('25', 'Lee un artículo de noticias y resúmelo', 'Lee una noticia actual y escribe un resumen breve en tus propias palabras.', 'Lectura y Aprendizaje', 14, NULL, 10),
    ('26', 'Aprende un dato curioso nuevo y compártelo', 'Investiga algo interesante que no sabías y cuéntaselo a alguien.', 'Lectura y Aprendizaje', 8, NULL, 10),
    ('27', 'Escribe 5 frases en un idioma que estés aprendiendo', 'Construye 5 oraciones simples usando vocabulario nuevo.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('28', 'Juega una partida de ajedrez', 'Juega una partida completa con otra persona o contra ti mismo analizando cada jugada.', 'Juegos y Entretenimiento', 7, NULL, 20),
    ('29', 'Organiza un juego de cartas con tu familia', 'Enseña o aprende un juego de cartas nuevo con las personas que tengas cerca.', 'Juegos y Entretenimiento', 6, NULL, 15),
    ('30', 'Arma un rompecabezas', 'Dedica un rato a armar un rompecabezas, aunque sea por partes.', 'Juegos y Entretenimiento', 5, NULL, 15),
    ('31', 'Juega un juego de mesa con alguien', 'Elige cualquier juego de mesa que tengas disponible y juega una partida.', 'Juegos y Entretenimiento', 6, NULL, 15),
    ('32', 'Resuelve un crucigrama o sopa de letras', 'Ejercita tu mente con un pasatiempo de palabras.', 'Juegos y Entretenimiento', 10, NULL, 10),
    ('33', 'Aprende las reglas de un juego nuevo', 'Investiga cómo se juega algo que nunca has probado.', 'Juegos y Entretenimiento', 8, NULL, 10),
    ('34', 'Juega una partida de damas', 'Juega una partida completa de damas con otra persona.', 'Juegos y Entretenimiento', 6, NULL, 15),
    ('35', 'Organiza una noche de juegos con amigos', 'Convoca a un grupo pequeño para jugar cartas o juegos de mesa una noche.', 'Juegos y Entretenimiento', 12, NULL, 25),
    ('36', 'Cocina una receta nueva con lo que tengas en casa', 'Prepara un platillo que nunca hayas hecho, usando ingredientes disponibles.', 'Cocina y Gastronomía', 12, NULL, 25),
    ('37', 'Prepara un postre sencillo', 'Haz un postre rápido con pocos ingredientes.', 'Cocina y Gastronomía', 10, NULL, 20),
    ('38', 'Intenta una receta de otro país', 'Busca una receta típica de una cultura distinta a la tuya y prepárala.', 'Cocina y Gastronomía', 12, NULL, 25),
    ('39', 'Organiza tu despensa', 'Ordena y revisa los ingredientes que tienes disponibles en casa.', 'Cocina y Gastronomía', 8, NULL, 10),
    ('40', 'Prepara tu comida favorita desde cero', 'Cocina el platillo que más te gusta, sin usar preparados.', 'Cocina y Gastronomía', 12, NULL, 20),
    ('41', 'Prueba una receta vegetariana', 'Cocina un platillo sin carne, aunque no sea tu costumbre.', 'Cocina y Gastronomía', 12, NULL, 20),
    ('42', 'Hornea pan casero', 'Prepara pan desde cero, siguiendo una receta básica.', 'Cocina y Gastronomía', 14, NULL, 30),
    ('43', 'Prepara una bebida o smoothie saludable', 'Combina frutas o ingredientes frescos en una bebida nutritiva.', 'Cocina y Gastronomía', 8, NULL, 10),
    ('44', 'Practica 15 minutos con tu instrumento', 'Toca tu instrumento musical durante al menos 15 minutos seguidos.', 'Música', 8, NULL, 20),
    ('45', 'Escucha un álbum completo de un género que no conoces', 'Elige un género musical fuera de tu zona de confort y escúchalo completo, prestando atención.', 'Música', 8, NULL, 10),
    ('46', 'Aprende un acorde nuevo en tu instrumento', 'Investiga y practica un acorde que no domines todavía.', 'Música', 8, NULL, 15),
    ('47', 'Escribe la letra de una canción corta', 'Escribe unos versos sobre cualquier tema que te inspire.', 'Música', 10, NULL, 15),
    ('48', 'Compón una melodía simple', 'Crea una melodía corta con tu instrumento, aunque sea básica.', 'Música', 10, NULL, 20),
    ('49', 'Haz una playlist con canciones que te inspiren', 'Reúne canciones que reflejen tu estado de ánimo actual.', 'Música', 8, NULL, 10),
    ('50', 'Aprende la letra de una canción nueva', 'Memoriza la letra completa de una canción que te guste.', 'Música', 6, NULL, 15),
    ('51', 'Toca tu canción favorita', 'Practica hasta poder tocar tu canción favorita en tu instrumento.', 'Música', 8, NULL, 25),
    ('52', 'Practica un riff', 'Elige un riff corto y repítelo hasta tocarlo con fluidez.', 'Música', 8, NULL, 20),
    ('53', 'Toca una escala', 'Practica una escala mayor completa de principio a fin.', 'Música', 6, NULL, 15),
    ('54', 'Practica un ritmo básico', 'Repite un patrón de ritmo sencillo durante unos minutos.', 'Música', 8, NULL, 20),
    ('55', 'Afina tu instrumento y toca una pieza corta', 'Dedica un momento a afinar el instrumento y practicar una melodía breve.', 'Música', 8, NULL, 20),
    ('56', 'Aprende un acorde nuevo', 'Busca un acorde que no domines y practícalo hasta que suene limpio.', 'Música', 6, NULL, 15),
    ('57', 'Practica una melodía sencilla', 'Elige una melodía corta y tócala de principio a fin varias veces.', 'Música', 8, NULL, 15),
    ('58', 'Improvisa una línea de bajo simple', 'Crea una línea de bajo corta siguiendo un ritmo constante.', 'Música', 10, NULL, 20),
    ('59', 'Practica escalas', 'Recorre varias escalas básicas para calentar antes de tocar una canción.', 'Música', 6, NULL, 15),
    ('60', 'Reseña un libro que hayas terminado', 'Escribe una breve reseña: qué te gustó, qué no, y a quién se lo recomendarías.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('61', 'Compara dos autores que te gusten', 'Piensa en qué se parecen y en qué difieren sus estilos de escritura.', 'Lectura y Aprendizaje', 12, NULL, 15),
    ('62', 'Lee un poema y reflexiona sobre él', 'Elige un poema corto, léelo dos veces y escribe qué te hizo sentir.', 'Lectura y Aprendizaje', 10, NULL, 10),
    ('63', 'Lleva un diario de lectura durante la semana', 'Anota cada día cuánto leíste y una idea que te haya quedado.', 'Lectura y Aprendizaje', 10, NULL, 20),
    ('64', 'Relee un capítulo subrayando las ideas clave', 'Vuelve a un capítulo que ya leíste y marca lo más importante.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('65', 'Busca un libro nuevo por recomendación de alguien', 'Pídele a alguien que te recomiende un libro y anótalo para leerlo pronto.', 'Lectura y Aprendizaje', 8, NULL, 10),
    ('66', 'Practica pronunciación con audio', 'Escucha frases cortas en el idioma que aprendes y repítelas en voz alta.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('67', 'Traduce la letra de una canción', 'Elige una canción en el idioma que estudias y traduce su letra a tu idioma.', 'Lectura y Aprendizaje', 12, NULL, 20),
    ('68', 'Ve un video corto en el idioma con subtítulos', 'Mira un video de pocos minutos en el idioma que aprendes, con subtítulos de apoyo.', 'Lectura y Aprendizaje', 10, NULL, 15),
    ('69', 'Escribe un diario breve en el idioma que aprendes', 'Redacta unas líneas sobre tu día usando el vocabulario que ya conoces.', 'Lectura y Aprendizaje', 12, NULL, 15),
    ('70', 'Aprende 5 modismos o expresiones comunes', 'Investiga expresiones típicas del idioma que estudias y su significado.', 'Lectura y Aprendizaje', 12, NULL, 15),
    ('71', 'Practica una conversación básica con alguien', 'Intenta mantener una conversación corta y simple en el idioma que aprendes.', 'Lectura y Aprendizaje', 10, NULL, 20),
    ('72', 'Dibuja usando solo tres colores', 'Elige únicamente tres colores y crea un dibujo completo combinándolos de distintas formas.', 'Arte', 6, NULL, 15),
    ('73', 'Crea una tarjeta hecha a mano', 'Diseña una tarjeta para alguien especial usando dibujos, letras y materiales que tengas disponibles.', 'Arte', 6, NULL, 15),
    ('74', 'Dibuja la habitación de tus sueños', 'Imagina cómo sería tu habitación ideal y dibuja su distribución, colores y decoración.', 'Arte', 8, NULL, 20),
    ('75', 'Reinterpreta una obra famosa a tu estilo', 'Elige una obra de arte conocida y crea tu propia versión cambiando colores, formas o detalles.', 'Arte', 10, NULL, 25),
    ('76', 'Diseña un personaje original', 'Inventa un personaje desde cero y dibuja su apariencia, ropa y algún detalle que represente su personalidad.', 'Arte', 8, NULL, 20),
    ('77', 'Crea una composición con sombras', 'Coloca objetos frente a una fuente de luz y usa sus sombras como base para crear un dibujo creativo.', 'Arte', 8, NULL, 20),
    ('78', 'Completa un circuito de ejercicio de 3 rondas', 'Haz tres rondas combinando sentadillas, plancha y saltos suaves, descansando cuando lo necesites.', 'Deportes y Salud', 12, NULL, 25),
    ('79', 'Baila durante 20 minutos', 'Pon varias canciones que te gusten y mantente en movimiento durante 20 minutos.', 'Deportes y Salud', 6, NULL, 20),
    ('80', 'Practica equilibrio durante 10 minutos', 'Alterna posiciones sencillas de equilibrio, como mantenerte sobre un pie y cambiar de lado.', 'Deportes y Salud', 6, NULL, 10),
    ('81', 'Haz un reto de 40 sentadillas', 'Completa 40 sentadillas a tu ritmo, dividiéndolas en varias series si es necesario.', 'Deportes y Salud', 12, NULL, 15),
    ('82', 'Practica pases contra una pared', 'Usa un balón para practicar control y precisión haciendo pases contra una pared durante 15 minutos.', 'Deportes y Salud', 8, NULL, 15),
    ('83', 'Haz una caminata con cambios de ritmo', 'Camina durante 20 minutos alternando periodos tranquilos con otros un poco más rápidos.', 'Deportes y Salud', 10, NULL, 20),
    ('84', 'Resuelve un sudoku', 'Completa un sudoku del nivel que prefieras intentando resolverlo sin buscar las respuestas.', 'Juegos y Entretenimiento', 10, NULL, 15),
    ('85', 'Juega una ronda de mímica', 'Elige palabras o acciones al azar y trata de representarlas sin hablar para que alguien las adivine.', 'Juegos y Entretenimiento', 6, NULL, 15),
    ('86', 'Haz un concurso de preguntas con alguien', 'Preparen preguntas de cultura general y compitan para ver quién responde correctamente más veces.', 'Juegos y Entretenimiento', 8, NULL, 20),
    ('87', 'Crea un juego de memoria con cartas', 'Forma pares con cartas o papeles y juega intentando recordar dónde está cada pareja.', 'Juegos y Entretenimiento', 5, NULL, 15),
    ('88', 'Resuelve cinco acertijos', 'Busca o inventa cinco acertijos y trata de resolverlos antes de revisar las respuestas.', 'Juegos y Entretenimiento', 8, NULL, 15),
    ('89', 'Inventa un juego con reglas propias', 'Crea un juego sencillo, define sus reglas y pruébalo con otra persona para ver si funciona.', 'Juegos y Entretenimiento', 8, NULL, 25),
    ('90', 'Prepara un desayuno equilibrado', 'Combina alimentos que tengas en casa para preparar un desayuno completo y diferente al habitual.', 'Cocina y Gastronomía', 10, NULL, 20),
    ('91', 'Prepara una ensalada con al menos cinco colores', 'Usa frutas o vegetales de distintos colores para crear una ensalada variada y llamativa.', 'Cocina y Gastronomía', 8, NULL, 15),
    ('92', 'Haz una salsa o aderezo casero', 'Prepara desde cero una salsa o aderezo sencillo para acompañar una comida.', 'Cocina y Gastronomía', 10, NULL, 15),
    ('93', 'Cocina una receta con máximo cinco ingredientes', 'Elige una preparación sencilla y complétala usando cinco ingredientes o menos.', 'Cocina y Gastronomía', 12, NULL, 20),
    ('94', 'Prepara un snack saludable', 'Crea una merienda sencilla usando frutas, vegetales u otros ingredientes que tengas disponibles.', 'Cocina y Gastronomía', 8, NULL, 10),
    ('95', 'Presenta un plato de forma creativa', 'Prepara una comida sencilla y dedica unos minutos a organizarla visualmente como si fuera de restaurante.', 'Cocina y Gastronomía', 8, NULL, 15),
    ('96', 'Identifica tres plantas o árboles de tu entorno', 'Observa las plantas cercanas e intenta conocer el nombre de al menos tres especies diferentes.', 'Naturaleza', 8, NULL, 15),
    ('97', 'Observa el cielo durante 15 minutos', 'Busca un lugar tranquilo y observa las nubes, sus formas, movimientos o cambios de color.', 'Naturaleza', 6, NULL, 10),
    ('98', 'Escucha e identifica cinco sonidos de la naturaleza', 'Permanece unos minutos en silencio e intenta distinguir sonidos como aves, viento, hojas, insectos o agua.', 'Naturaleza', 6, NULL, 10),
    ('99', 'Recoge basura de un espacio natural cercano', 'Dedica unos minutos a recoger residuos visibles en un parque, jardín o zona verde, evitando objetos peligrosos.', 'Naturaleza', 10, NULL, 25),
    ('100', 'Planta una semilla y cuida su crecimiento', 'Siembra una semilla en tierra o en una maceta y déjala preparada para observar cómo cambia con los días.', 'Naturaleza', 6, NULL, 20),
    ('101', 'Busca seis colores diferentes en la naturaleza', 'Explora un espacio al aire libre e identifica seis colores distintos presentes en hojas, flores, piedras o el paisaje.', 'Naturaleza', 5, NULL, 15)
) AS v(external_id, title, description, category, min_age, max_age, points)
LEFT JOIN public.activity_categories c ON c.name = v.category
WHERE NOT EXISTS (
  SELECT 1 FROM public.activities a WHERE a.external_id = v.external_id
);

-- 2. GUSTOS DE CADA ACTIVIDAD
-- Sin estas relaciones el motor de recomendación no puede medir afinidad: una
-- actividad sin etiquetas encaja con todo el mundo por igual y las sugerencias
-- se vuelven aleatorias.
INSERT INTO public.activity_likes (activity_id, like_id)
SELECT a.id, l.id
FROM (VALUES
    ('1', 'Arte'),
    ('2', 'Arte'),
    ('3', 'Arte'),
    ('4', 'Arte'),
    ('5', 'Arte'),
    ('6', 'Arte'),
    ('7', 'Arte'),
    ('8', 'Arte'),
    ('9', 'Arte'),
    ('10', 'Deportes'),
    ('10', 'Naturaleza'),
    ('11', 'Deportes'),
    ('11', 'Naturaleza'),
    ('12', 'Deportes'),
    ('13', 'Deportes'),
    ('14', 'Deportes'),
    ('15', 'Deportes'),
    ('16', 'Deportes'),
    ('17', 'Deportes'),
    ('17', 'Naturaleza'),
    ('18', 'Deportes'),
    ('19', 'Lectura'),
    ('20', 'Lectura'),
    ('21', 'Lectura'),
    ('22', 'Lectura'),
    ('23', 'Lectura'),
    ('24', 'Lectura'),
    ('25', 'Lectura'),
    ('26', 'Lectura'),
    ('27', 'Lectura'),
    ('36', 'Cocina'),
    ('37', 'Cocina'),
    ('38', 'Cocina'),
    ('39', 'Cocina'),
    ('40', 'Cocina'),
    ('41', 'Cocina'),
    ('42', 'Cocina'),
    ('43', 'Cocina'),
    ('44', 'Música'),
    ('45', 'Música'),
    ('46', 'Música'),
    ('47', 'Música'),
    ('48', 'Música'),
    ('49', 'Música'),
    ('50', 'Música'),
    ('51', 'Música'),
    ('52', 'Música'),
    ('53', 'Música'),
    ('54', 'Música'),
    ('55', 'Música'),
    ('56', 'Música'),
    ('57', 'Música'),
    ('58', 'Música'),
    ('59', 'Música'),
    ('60', 'Lectura'),
    ('61', 'Lectura'),
    ('62', 'Lectura'),
    ('63', 'Lectura'),
    ('64', 'Lectura'),
    ('65', 'Lectura'),
    ('66', 'Lectura'),
    ('67', 'Lectura'),
    ('68', 'Lectura'),
    ('69', 'Lectura'),
    ('70', 'Lectura'),
    ('71', 'Lectura'),
    ('72', 'Arte'),
    ('73', 'Arte'),
    ('74', 'Arte'),
    ('75', 'Arte'),
    ('76', 'Arte'),
    ('77', 'Arte'),
    ('78', 'Deportes'),
    ('79', 'Deportes'),
    ('79', 'Música'),
    ('80', 'Deportes'),
    ('81', 'Deportes'),
    ('82', 'Deportes'),
    ('83', 'Deportes'),
    ('83', 'Naturaleza'),
    ('90', 'Cocina'),
    ('91', 'Cocina'),
    ('92', 'Cocina'),
    ('93', 'Cocina'),
    ('94', 'Cocina'),
    ('95', 'Cocina'),
    ('95', 'Arte'),
    ('96', 'Naturaleza'),
    ('97', 'Naturaleza'),
    ('98', 'Naturaleza'),
    ('99', 'Naturaleza'),
    ('100', 'Naturaleza'),
    ('101', 'Naturaleza'),
    ('101', 'Arte')
) AS v(external_id, name)
JOIN public.activities a ON a.external_id = v.external_id
JOIN public.likes l ON l.name = v.name
ON CONFLICT DO NOTHING;

-- 3. INTERESES DE CADA ACTIVIDAD
INSERT INTO public.activity_interests (activity_id, interest_id)
SELECT a.id, i.id
FROM (VALUES
    ('1', 'Mejorar creatividad'),
    ('2', 'Mejorar creatividad'),
    ('3', 'Mejorar creatividad'),
    ('4', 'Mejorar creatividad'),
    ('5', 'Mejorar creatividad'),
    ('6', 'Mejorar creatividad'),
    ('6', 'Aprender cosas nuevas'),
    ('7', 'Mejorar creatividad'),
    ('8', 'Mejorar creatividad'),
    ('9', 'Mejorar creatividad'),
    ('10', 'Hacer ejercicio'),
    ('11', 'Hacer ejercicio'),
    ('12', 'Hacer ejercicio'),
    ('13', 'Hacer ejercicio'),
    ('14', 'Hacer ejercicio'),
    ('15', 'Hacer ejercicio'),
    ('16', 'Hacer ejercicio'),
    ('17', 'Hacer ejercicio'),
    ('18', 'Hacer ejercicio'),
    ('19', 'Leer más'),
    ('20', 'Aprender un idioma'),
    ('21', 'Aprender cosas nuevas'),
    ('22', 'Leer más'),
    ('23', 'Aprender cosas nuevas'),
    ('24', 'Aprender un idioma'),
    ('25', 'Leer más'),
    ('26', 'Aprender cosas nuevas'),
    ('27', 'Aprender un idioma'),
    ('28', 'Aprender cosas nuevas'),
    ('29', 'Aprender cosas nuevas'),
    ('30', 'Aprender cosas nuevas'),
    ('31', 'Aprender cosas nuevas'),
    ('32', 'Aprender cosas nuevas'),
    ('33', 'Aprender cosas nuevas'),
    ('34', 'Aprender cosas nuevas'),
    ('35', 'Aprender cosas nuevas'),
    ('36', 'Aprender cosas nuevas'),
    ('37', 'Aprender cosas nuevas'),
    ('38', 'Aprender cosas nuevas'),
    ('40', 'Aprender cosas nuevas'),
    ('41', 'Aprender cosas nuevas'),
    ('42', 'Aprender cosas nuevas'),
    ('44', 'Aprender cosas nuevas'),
    ('45', 'Aprender cosas nuevas'),
    ('46', 'Aprender cosas nuevas'),
    ('47', 'Mejorar creatividad'),
    ('48', 'Mejorar creatividad'),
    ('50', 'Aprender cosas nuevas'),
    ('51', 'Aprender cosas nuevas'),
    ('52', 'Aprender cosas nuevas'),
    ('53', 'Aprender cosas nuevas'),
    ('54', 'Aprender cosas nuevas'),
    ('55', 'Aprender cosas nuevas'),
    ('56', 'Aprender cosas nuevas'),
    ('57', 'Aprender cosas nuevas'),
    ('58', 'Mejorar creatividad'),
    ('59', 'Aprender cosas nuevas'),
    ('60', 'Leer más'),
    ('61', 'Leer más'),
    ('62', 'Leer más'),
    ('63', 'Leer más'),
    ('64', 'Leer más'),
    ('65', 'Leer más'),
    ('66', 'Aprender un idioma'),
    ('67', 'Aprender un idioma'),
    ('68', 'Aprender un idioma'),
    ('69', 'Aprender un idioma'),
    ('70', 'Aprender un idioma'),
    ('71', 'Aprender un idioma'),
    ('72', 'Mejorar creatividad'),
    ('73', 'Mejorar creatividad'),
    ('74', 'Mejorar creatividad'),
    ('75', 'Mejorar creatividad'),
    ('75', 'Aprender cosas nuevas'),
    ('76', 'Mejorar creatividad'),
    ('77', 'Mejorar creatividad'),
    ('78', 'Hacer ejercicio'),
    ('79', 'Hacer ejercicio'),
    ('80', 'Hacer ejercicio'),
    ('81', 'Hacer ejercicio'),
    ('82', 'Hacer ejercicio'),
    ('83', 'Hacer ejercicio'),
    ('84', 'Aprender cosas nuevas'),
    ('85', 'Mejorar creatividad'),
    ('86', 'Aprender cosas nuevas'),
    ('87', 'Aprender cosas nuevas'),
    ('88', 'Aprender cosas nuevas'),
    ('89', 'Mejorar creatividad'),
    ('90', 'Aprender cosas nuevas'),
    ('91', 'Aprender cosas nuevas'),
    ('92', 'Aprender cosas nuevas'),
    ('93', 'Mejorar creatividad'),
    ('94', 'Aprender cosas nuevas'),
    ('95', 'Mejorar creatividad'),
    ('96', 'Aprender cosas nuevas'),
    ('97', 'Mejorar creatividad'),
    ('98', 'Aprender cosas nuevas'),
    ('99', 'Aprender cosas nuevas'),
    ('100', 'Aprender cosas nuevas'),
    ('101', 'Mejorar creatividad')
) AS v(external_id, name)
JOIN public.activities a ON a.external_id = v.external_id
JOIN public.interests i ON i.name = v.name
ON CONFLICT DO NOTHING;

-- 4. RECURSOS QUE REQUIERE CADA ACTIVIDAD
INSERT INTO public.activity_resources (activity_id, resource_id)
SELECT a.id, r.id
FROM (VALUES
    ('1', 'Pinturas'),
    ('2', 'Lápices'),
    ('3', 'Lápices'),
    ('5', 'Pinturas'),
    ('6', 'Computadora'),
    ('8', 'Lápices'),
    ('9', 'Computadora'),
    ('11', 'Bicicleta'),
    ('12', 'Balón'),
    ('16', 'Balón'),
    ('19', 'Libros'),
    ('21', 'Computadora'),
    ('22', 'Libros'),
    ('23', 'Computadora'),
    ('25', 'Computadora'),
    ('28', 'Ajedrez'),
    ('29', 'Cartas'),
    ('35', 'Cartas'),
    ('38', 'Computadora'),
    ('44', 'Instrumento musical'),
    ('45', 'Computadora'),
    ('46', 'Instrumento musical'),
    ('48', 'Instrumento musical'),
    ('49', 'Computadora'),
    ('51', 'Instrumento musical'),
    ('52', 'Instrumento musical'),
    ('53', 'Instrumento musical'),
    ('54', 'Instrumento musical'),
    ('55', 'Instrumento musical'),
    ('56', 'Instrumento musical'),
    ('57', 'Instrumento musical'),
    ('58', 'Instrumento musical'),
    ('59', 'Instrumento musical'),
    ('60', 'Libros'),
    ('62', 'Libros'),
    ('64', 'Libros'),
    ('66', 'Computadora'),
    ('67', 'Computadora'),
    ('68', 'Computadora'),
    ('72', 'Lápices'),
    ('74', 'Lápices'),
    ('75', 'Computadora'),
    ('76', 'Lápices'),
    ('77', 'Lápices'),
    ('82', 'Balón'),
    ('87', 'Cartas')
) AS v(external_id, name)
JOIN public.activities a ON a.external_id = v.external_id
JOIN public.resources r ON r.name = v.name
ON CONFLICT DO NOTHING;

COMMIT;

-- 5. COMPROBACIÓN
SELECT
  count(*) FILTER (WHERE source = 'mockapi') AS importadas,
  count(*) FILTER (WHERE source = 'catalog') AS propias,
  count(*) FILTER (WHERE category_id IS NULL) AS sin_categoria_libre,
  count(*) FILTER (WHERE NOT EXISTS (
    SELECT 1 FROM public.activity_interests ai WHERE ai.activity_id = a.id
  ) AND NOT EXISTS (
    SELECT 1 FROM public.activity_likes al WHERE al.activity_id = a.id
  )) AS comodines_sin_etiquetas
FROM public.activities a
WHERE a.is_active;
